name: 'rest_client'
description: 'A Dart implementation of the a REST client that supports using an Isolate for decoding.'
version: '2.2.1+12'
homepage: 'https://github.com/peiffer-innovations/rest_client'

environment: 
  sdk: '>=2.19.0 <4.0.0'

dependencies: 
  http: '^1.0.0'
  intl: '^0.18.1'
  json_class: '^2.2.1+3'
  logging: '^1.1.1'
  meta: '^1.8.0'
  uuid: '^3.0.7'

dev_dependencies: 
  test: '^1.24.3'

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
